#!/bin/sh
echo "                                                           "
echo "        The Skin KravenHD is now being installed...        "
echo "                                                           "
