#!/bin/sh
if [ -d /usr/share/enigma2/KravenHD ]; then
cp /usr/share/enigma2/KravenHD/skin.xml /tmp
fi
if [ -d /usr/lib/enigma2/python/Plugins/Extensions/MyKravenHD ]; then
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MyKravenHD
fi
echo "                                                           "
echo " .##....##.########.....###....##.....##.########.##....## "
echo " .##...##..##.....##...##.##...##.....##.##.......###...## "
echo " .##..##...##.....##..##...##..##.....##.##.......####..## "
echo " .#####....########..##.....##.##.....##.######...##.##.## "
echo " .##..##...##...##...#########..##...##..##.......##..#### "
echo " .##...##..##....##..##.....##...##.##...##.......##...### "
echo " .##....##.##.....##.##.....##....###....########.##....## "
echo "                    .##.....##.########.                   "
echo "                    .##.....##.##.....##                   "
echo "                    .##.....##.##.....##                   "
echo "                    .#########.##.....##                   "
echo "                    .##.....##.##.....##                   "
echo "                    .##.....##.##.....##                   "
echo "                    .##.....##.########.                   "
echo "                                                           "  
echo "        The Skin KravenHD is now being installed...        "
echo "                                                           "
