#!/bin/sh
echo "                                                           "
echo "        The Skin KravenHD is now being removed...           "
echo "                                                           "
